require "plugins"
-- all configurations for plugins
require "plugins/configs/cmp"
require "plugins/configs/gitsigns"
require "plugins/configs/indentblankline"
require "plugins/configs/lightline"
require "plugins/configs/lspinstaller"
require "plugins/configs/lspconfig"
require "plugins/configs/nvim-dap"
require "plugins/configs/nvim-dap-python"
require "plugins/configs/lspsignature"
require "plugins/configs/netrw"
require "plugins/configs/nvim-lint"
require "plugins/configs/nvim-treesitter"
require "plugins/configs/startup"
require "plugins/configs/telescope"
-- all settings
require "settings/all"
